version: "3.7"

services:
  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DB_URL=postgres://user:123456789@postgres_db:5432/invoice
      - REDIS=redis://cache
    networks:
      - invoice-network
    depends_on:
      - redis_db
      - postgres_db

  api_create_pdf:
    build: ./api_createPdf
    command: npm run start
    restart: unless-stopped
    environment:
      - REDIS=redis://cache
    depends_on:
      - api
      - redis_db
    networks:
      - invoice-network
    volumes:
      - pdf_file:/usr/src/app/uploads

  api_send_letters:
    build: ./api_sendLetter
    command: npm run start
    restart: unless-stopped
    environment:
      - REDIS=redis://cache
      - API_KEY_MAILGAN=33e81353986c5590c2296802c00ea53b-73e57fef-835957c8
      - DOMAIN_MAILGAN=sandboxff937e9201a1427eb3f0ea3ebee091ac.mailgun.org
    depends_on:
      - api
      - redis_db
    networks:
      - invoice-network
    volumes:
      - pdf_file:/usr/src/app/uploads

  redis_db:
    image: redis:latest
    container_name: cache
    expose:
      - 6379
    networks:
      - invoice-network

  postgres_db:
    image: postgres:13.2-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=invoice
    expose:
      - 5432
    networks:
      - invoice-network

networks:
  invoice-network:
    driver: bridge

volumes:
  pdf_file: