version: "3.7"

services:
  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DB_URL=mongodb://api_db:27017
      - REDIS=redis://cache
      - EMAIL=
      - API_KEY_MAILGAN=
      - DOMAIN_MAILGAN=
    depends_on:
      - redis_db
      - api_db
    networks:
      - invoice-network

  redis_db:
    image: redis:latest
    container_name: cache
    expose:
      - 6379
    networks:
      - invoice-network

  api_db:
    image: mongo:latest
    container_name: invoice-api-db
    ports:
    - 27017:27017
    networks:
      - invoice-network

networks:
  invoice-network:
    driver: bridge
